void str_overwrite_stdout()
void str_trim_lf (char* arr, int length)
void catch_ctrl_c_and_exit(int sig)
void * send_msg_handler(void *) 
void * recv_msg_handler(void *) 
int main(int argc, char **argv)